### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [picklefactory/p-g-wodehouse_the-little-nugget#1]
# Typography

- [x] chapter-1-1: In 3c6e346480fc9d55392f78435db62040fe475398, it seems you accidentally deleted a line, `<p>“I’ll have <em>mine</em> here,” said Cynthia.</p>`, which should follow the “My poor child! etc. etc.” line. [p. 14](https://babel.hathitrust.org/cgi/pt?id=umn.31951002001434n&seq=24)
- [x] Revert 575911851d22c16d071e8f2a6f82901d5c244a9c. That is a stylistic variation on the use of ellipses we frequently see in the public domain time period.
- [x] 185a7ce36a1c72b06d82263499d48bbe775493a3, 58d03c4e8ad4410969246d19c0e89e74766698dd: Usually we don’t want to change the typography of letters, just add semantics to the appropriate parts of the text. I would restore the original punctuation and line structure, while leaving the semantics you added.

# Spelling

- [x] 08a4f2b6eff7d517fb5f4e099889ef7a8e1bbb80: Let’s revert this, it seems like a representation of vernacular speech.

# Semantics

- [x] chapter-1-1: In “to sketch the house from the east. I chose the east because...,” the instances of “east” should get `<strong>`. In the original text, they are printed in small-caps (which is why PG had them in all caps in the source text). [p. 17](https://babel.hathitrust.org/cgi/pt?id=umn.31951002001434n&seq=27)
- [x] These words are found in Merriam-Webster and do not need italics:

* hara-kiri
* au fond
* bête noire

# CSS

- [x] It is not a big deal on a project this small, but in general we prefer to use comments in local.css to group together thematically connected CSS rules (e.g. verse, letters, etc.). Usually we have a `/* Begin x*/` and `/* End x */` comment to make things clear. It is a good habit to get into as you start working on larger and more complex projects.

# Metadata

- [x] `<dc:description id="description">` seems a little too long to me. This is supposed to be a short, pithier description.
- [x] It should say `known as the Little Nugget` or `known as “The Little Nugget”` in the long description. I don’t think it is correct to capitalize “The” without quotation marks here.
- [x] I don’t think we need as extensive of a biography of Wodehouse in the long description, since most of that doesn’t have anything to do with this book and we already have so many Wodehouse works in the collection. I would cut it down to whatever is relevant to this particular book.

**Comment by picklefactory** [comment]
I somehow had to do zero CSS work on my first project, and of all of the elements of producing these it's the part I have the least experience with – so if any of this looked like someone just attempting to get `se lint` to stop complaining, that is accurate! I wound up deleting a bunch of extraneous/un-targeted rules and it all got somewhat shuffled together.

Which is just to say, the of the issues above, getting the line structure and formatting right on the letters is the only thing I'm a bit uncertain on. I will give it a go and see how it previews and update the issue here.

What's the deal with the capitalized ordinals? Generally in accordance with style guide I have been going around un-capitalizing them when used as a direction as opposed to a proper noun, but the bold-small-caps typography seems to indicate something specific and I have no idea what I missed.

Thanks for the review!

**Comment by picklefactory** [comment]
Excuse me – wrong button – I didn't mean to mark that as closed just yet!

**Comment by picklefactory** [comment]
OK, I gave the letters another try to better match the formatting of the scan. 

The main thing I cannot figure out is what to do with the signature in chapter-2-11, my CSS is not advanced enough to know how to right-justify and left-justify the same line of text; it simply shows up as a next sentence instead of at the right side of the page. Giving it its own `<p>` element doesn't right-align the text on the next line, which makes sense. But it feels like I would need some CSS for this specific instance only? Or maybe not, since this is the only one, and Wodehouse/publisher doesn't bother with a new line for the signature in the extremely brief other letter in chapter-2-6.

I've continued to leave out the quotation marks around the correspondence in the scan.

At any rate, it is still correct enough to pass `se lint`.

Thanks

**Comment by weijia-cheng** [comment]
For the signature in chapter-2-11, you can just put it into a footer. It's ok if that starts on a new line.

For the capitalized ordinal directions, I am not sure I understand what the original intent of the author was, but the small caps styling seems purposeful here and we may as well replicate it.

**Comment by picklefactory** [comment]
OK – all of the issues here should be resolved, `se lint` checks out.

**Comment by weijia-cheng** [comment]
- [x] I don't think the revert of 08a4f2b worked. Commit 785c902 is unrelated to the message.
- [x] Instead using `<span>` for the deitalicized dictionary words, remove the semantics altogether.
- [x] There is an extra space before the `—In haste` in the letter in chapter-2-6.
- [x] Rerun `typogrify`.
- [x] Rerun `clean`.

**Comment by picklefactory** [comment]
I have no idea what was up with that one revert. I need more practice doing reverts! I rebased to that and did it again properly.

Regarding the deitalicized dictionary words – I believe I was thinking of SEMoS 5.3.1.1 where it says "A `<span xml:lang="TAG">` element is used to wrap text that has non-English pronunciation but that does not need further visual styling." But it sounds like I should _first_ apply SEMoS 8.2.9.4 which says "Words and phrases that are originally non-English in origin, but that can now be found in [Merriam-Webster’s](https://www.merriam-webster.com/) basic online search results, are not italicized" and just exclude anything that's in the MW English dictionary to begin with, ignoring whether it was italicized as a foreign word in the original text (since it's "English enough" now). Is that closer to the right idea?

**Comment by weijia-cheng** [comment]
Yes, also rule [8.2.9.2](https://standardebooks.org/manual/1.8.0/single-page#8.2.9.2) clarifies when the `<span xml:lang="LANGUAGE">` pattern is usually used.

**Comment by picklefactory** [comment]
OK, this makes sense -- "if it might be mispronounced", but anything already in MW English is going to be able to use the pronunciation given therein. This did not totally click for me until now. Thank you!!

**Comment by picklefactory** [comment]
The question to ask myself is not "does this word have a non-English pronunciation?" – it's "if a person looks up this word in a common online English dictionary, will they see a pronunciation guide for it?"
